apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: opentelemetry-kube-stack
    repo: oci://myacrvinayh.azurecr.io/helm
    version: 0.6.2
    releaseName: opentelemetry-kube-stack
    namespace: o11y-otel
    valuesFile: elastic-values.yaml